### PR TITLE
Minor refactoring, new options and more documentation

### PR DESCRIPTION
**Pull request by janvonde**
During our tests we recognized, that the local configured rules overwrote the maintainers ones. This is the reason why we merged the functionality of the needrestart_customisations.conf into the main needrestart.conf.

The package in Ubuntu Linux 16.04 includes further rules so we updated the template as well.

Two new parameters were introduced to disable the kernel hints and set the preferred_ui back to defaults debconf, the changes are backwards compatible.

Not backwards compatible is the cleanup of the ignorelist hash. This is a good example in the README.md file, but shouldn't be a default setting IMHO.

The documentation was updated to reflect all this changes as well as some cleanup.

Please note, that the changes proposed in #1 were not merged into this PR.

### CODE REVIEW

**Comment by janvonde** [comment]
@willemb or @sheldonh, any chance to get this PR merged and a new version released on puppet forge?

**Comment by WBasson** [comment]
Hi

We plan on looking at this early-ish next week.

**Comment by janvonde** [comment]
@WBasson thanks 😃

**Comment by WBasson** [comment]
Should $_install not be $install at the bottom of init?

**Comment by WBasson** [comment]
@janvonde Can you elaborate on "the local configured rules overwrote the maintainers ones" ?
From our perspective, that is entirely the point of the local file. We do not, for instance, want the maintainer to be able to dictate that mysql must be automatically restarted.

**Comment by janvonde** [comment]
@WBasson The maintainers needrestart.conf has some good default values. This is the reason for  062640dfed92c70944b2867dcbff44d903f957c0. I want to use this (IMHO) good default values and add my additional ones. Like: "do not restart tomcat, do not restart libvirt-bin" etc. If I use the local config file as it was before my settings are overwriting the ones specified in the needrestart.conf file. They are not merged. This means that this whole section in the needrestart.conf currently doesn't make sense because it is not interpreted anyway. I think this is the reason for z3rogate/puppet-needrestart@2692a906ec76c856d448e6113450df1c1a581c06 as well.

**Comment by WBasson** [comment]
This sounds really counter to what the point of /etc/needrestart/conf.d/ is. Unless you think upstream intends for you to first copy what they have into there, then add your customizations to another file.

**Comment by janvonde** [comment]
@WBasson I will check it again and open an issue upstream if there is a problem. Otherwise I will update my PR. According to liske/needrestart#13 it should work the way you mention...

**Comment by janvonde** [comment]
@WBasson I don't know what I checked before, but you were right. The local config file is not overwriting the main section. I reverted the commit.

**Comment by janvonde** [comment]
@WBasson I rolled out this module now this morning and had one last fix. everything else is working so far. From my side this PR is finished.

**Comment by janvonde** [comment]
thanks!

**Pull request merged**
